### ISSUE TITLE
Joint order in config file does not match the joint order in walking-controller retargetting for the real and simulated robot.

### ISSUE THREAD

**Issue by vigisushrutha23** [hsp-iit/ergocub-bimanual#1]
The joint order in the walking controller retargetting is as follows;
"torso_pitch", "torso_roll", "torso_yaw",
                                 "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow", "l_wrist_roll", "l_wrist_pitch", "l_wrist_yaw",
                                 "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow", "r_wrist_roll", "r_wrist_pitch", "r_wrist_yaw"

This is different from the one in the config file. The local version of the branch  https://github.com/Woolfrey/ergocub-bimanual/tree/on_ergocubSN000 has the right order and will be committed later. @Woolfrey . Maybe later I can give a pull request with branch on robot.

**Comment by Woolfrey** [comment]
@vigisushrutha23 I changed the order and updated the `joint_space_actions.ini` to match. Seems to be fine. Merged the results to main, so let me know how it runs on the real robot.
